### ISSUE TITLE
9.0.4: Cannot find module 'immer' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by hcharley** [immerjs/immer#826]
## 🐛 Bug Report

I was not having this problem until today, and I just upgraded packages to their latest. I'm seeing that updating to 9.0.3 caused this.

## Link to repro

I was not able to reproduce this with Codesandbox, but I will try this afternoon to.

## To Reproduce

TODO

## Observed behavior

A description of what behavior you observed and why you consider it faulty.

In a downstream package of a core module where I use immer and in the core module, I observe in VSCode that immer cannot be found.

## Expected behavior

To be able to use immer with included types.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:** 9.0.4
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by vnglst** [comment]
I also noticed this just now after upgrading to 9.0.4. Seems like the `dist` folder is missing in the npm package?

**Comment by mweststrate** [comment]
Should be fixed by 9.0.5

**Comment by hcharley** [comment]
@mweststrate Thanks. Confirming it looks fixed now.

**Comment by aranoe** [comment]
Happens in `9.0.6` as well.

Downgraded immer to fix it:
`yarn add immer@9.0.5`

**Comment by simontol** [comment]
Still here in `9.0.21`

**Comment by JingWZeng** [comment]
happens in 10.0.2

**Comment by jewseppi** [comment]
import { AnyArray } from 'immer/dist/internal';

Cannot find module 'immer/dist/internal' or its corresponding type declarations.ts(2307)

"immer": "^10.0.2",

**Comment by mweststrate** [comment]
"Dist/internal" is, as the name signals, not something you should be
importing from. Just add Array<any> instead?
